#!/bin/bash
set -e
cd /home/user

ls /home/user/app/.env 2>/dev/null && cat /home/user/app/.env || echo "FILE NOT FOUND"
mkdir -p /home/user/diagnostics
python3 - <<'EOF'
import os

dotenv_path = "/home/user/app/.env"
report_path = "/home/user/diagnostics/env_report.txt"

# Read and process .env file
entries = []
redacted_count = 0

with open(dotenv_path) as f:
    for line in f:
        line = line.rstrip('\n')
        if '=' in line:
            key, value = line.split('=', 1)
            if 'SECRET' in key or 'PASSWORD' in key:
                entries.append((key, '***REDACTED***'))
                redacted_count += 1
            else:
                entries.append((key, value))

total_count = len(entries)

# Get live env vars
hostname = os.environ.get('HOSTNAME', '')
shell = os.environ.get('SHELL', '')
user = os.environ.get('USER', '')

lines = []
lines.append("=== ENVIRONMENT DIAGNOSTICS REPORT ===")
lines.append("Generated by: support-tool v1.0")
lines.append("")
lines.append(f"[DOTENV FILE: {dotenv_path}]")
for key, value in entries:
    lines.append(f"{key}={value}")
lines.append("")
lines.append("[LIVE ENVIRONMENT]")
lines.append(f"HOSTNAME={hostname}")
lines.append(f"SHELL={shell}")
lines.append(f"USER={user}")
lines.append("")
lines.append("[SUMMARY]")
lines.append(f"Dotenv variables loaded: {total_count}")
lines.append(f"Sensitive keys redacted: {redacted_count}")

with open(report_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print("Report written successfully.")
EOF
cat /home/user/diagnostics/env_report.txt
