# test_final_state.py

import os
import pytest

REPORT_PSV = "/home/user/artifacts/report.psv"
INVENTORY_PSV = "/home/user/artifacts/inventory.psv"
REPO_IDS_TXT = "/home/user/artifacts/repo_ids.txt"

EXPECTED_REPORT_LINES = [
    "repo_id|artifact_name|checksum_sha256|size_bytes|upload_date",
    "R001|libssl.so.1.1|a3f1c29d8e4b56f0123456789abcdef0123456789abcdef0123456789abcdef01|2097152|2024-01-15",
    "R002|libcurl.so.4|b4e2d30a9f5c67e1234567890bcdef1234567890bcdef1234567890bcdef1234|1048576|2024-01-22",
    "R003|nginx-1.24.0|c5f3e41baf6d78f2345678901cdef2345678901cdef2345678901cdef234567|5242880|2024-02-03",
    "R004|python3.11|d6a4f52cbg7e89034567890123ef3456789012ef3456789012ef3456789012ef|31457280|2024-02-18",
    "R005|redis-server|e7b5063dch8f90145678901234f04567890123f04567890123f04567890123f0|8388608|2024-03-07",
]


def test_report_psv_exists():
    assert os.path.isfile(REPORT_PSV), (
        f"Output file '{REPORT_PSV}' does not exist. "
        "The report file must be generated by completing the task."
    )


def test_report_psv_is_readable():
    assert os.access(REPORT_PSV, os.R_OK), (
        f"File '{REPORT_PSV}' exists but is not readable."
    )


def test_report_psv_line_count():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    assert len(lines) == 6, (
        f"Expected exactly 6 lines in '{REPORT_PSV}' (1 header + 5 data rows), "
        f"but found {len(lines)} lines."
    )


def test_report_psv_no_trailing_blank_lines():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    # The file should not end with more than one newline (i.e., no blank trailing lines)
    assert not content.endswith("\n\n"), (
        f"File '{REPORT_PSV}' has trailing blank lines. "
        "The file must end without extra blank lines."
    )


def test_report_psv_no_trailing_whitespace_on_lines():
    with open(REPORT_PSV, "r") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        stripped_line = line.rstrip("\n")
        assert stripped_line == stripped_line.rstrip(), (
            f"Line {i+1} of '{REPORT_PSV}' has trailing whitespace.\n"
            f"  Line content: {stripped_line!r}"
        )


def test_report_psv_header():
    with open(REPORT_PSV, "r") as f:
        first_line = f.readline().rstrip("\n")

    expected_header = "repo_id|artifact_name|checksum_sha256|size_bytes|upload_date"
    assert first_line.strip() == expected_header, (
        f"Header of '{REPORT_PSV}' does not match expected.\n"
        f"  Expected: {expected_header!r}\n"
        f"  Actual:   {first_line.strip()!r}"
    )


def test_report_psv_column_count():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    for i, line in enumerate(lines):
        cols = line.split("|")
        assert len(cols) == 5, (
            f"Line {i+1} of '{REPORT_PSV}' should have 5 pipe-delimited columns, "
            f"but found {len(cols)}.\n  Line content: {line!r}"
        )


def test_report_psv_exact_content():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    assert len(lines) == len(EXPECTED_REPORT_LINES), (
        f"Expected {len(EXPECTED_REPORT_LINES)} lines in '{REPORT_PSV}', "
        f"but found {len(lines)} lines."
    )

    for i, (actual, expected) in enumerate(zip(lines, EXPECTED_REPORT_LINES)):
        assert actual == expected, (
            f"Line {i+1} of '{REPORT_PSV}' does not match expected content.\n"
            f"  Expected: {expected!r}\n"
            f"  Actual:   {actual!r}"
        )


def test_report_psv_first_column_is_repo_id():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    expected_repo_ids = ["repo_id", "R001", "R002", "R003", "R004", "R005"]

    for i, (line, expected_id) in enumerate(zip(lines, expected_repo_ids)):
        cols = line.split("|")
        actual_id = cols[0]
        assert actual_id == expected_id, (
            f"Line {i+1} of '{REPORT_PSV}': first column (repo_id) does not match.\n"
            f"  Expected: {expected_id!r}\n"
            f"  Actual:   {actual_id!r}"
        )


def test_report_psv_second_column_is_artifact_name():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    expected_artifact_names = [
        "artifact_name",
        "libssl.so.1.1",
        "libcurl.so.4",
        "nginx-1.24.0",
        "python3.11",
        "redis-server",
    ]

    for i, (line, expected_name) in enumerate(zip(lines, expected_artifact_names)):
        cols = line.split("|")
        actual_name = cols[1]
        assert actual_name == expected_name, (
            f"Line {i+1} of '{REPORT_PSV}': second column (artifact_name) does not match.\n"
            f"  Expected: {expected_name!r}\n"
            f"  Actual:   {actual_name!r}"
        )


def test_report_psv_version_and_arch_columns_absent():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    # Check that 'version' and 'arch' are not column headers
    header_cols = lines[0].split("|")
    assert "version" not in header_cols, (
        f"Column 'version' should not be present in '{REPORT_PSV}' header, "
        f"but found it. Header: {lines[0]!r}"
    )
    assert "arch" not in header_cols, (
        f"Column 'arch' should not be present in '{REPORT_PSV}' header, "
        f"but found it. Header: {lines[0]!r}"
    )


def test_report_psv_checksum_column():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    expected_checksums = [
        "checksum_sha256",
        "a3f1c29d8e4b56f0123456789abcdef0123456789abcdef0123456789abcdef01",
        "b4e2d30a9f5c67e1234567890bcdef1234567890bcdef1234567890bcdef1234",
        "c5f3e41baf6d78f2345678901cdef2345678901cdef2345678901cdef234567",
        "d6a4f52cbg7e89034567890123ef3456789012ef3456789012ef3456789012ef",
        "e7b5063dch8f90145678901234f04567890123f04567890123f04567890123f0",
    ]

    for i, (line, expected_checksum) in enumerate(zip(lines, expected_checksums)):
        cols = line.split("|")
        actual_checksum = cols[2]
        assert actual_checksum == expected_checksum, (
            f"Line {i+1} of '{REPORT_PSV}': third column (checksum_sha256) does not match.\n"
            f"  Expected: {expected_checksum!r}\n"
            f"  Actual:   {actual_checksum!r}"
        )


def test_report_psv_size_bytes_column():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    expected_sizes = [
        "size_bytes",
        "2097152",
        "1048576",
        "5242880",
        "31457280",
        "8388608",
    ]

    for i, (line, expected_size) in enumerate(zip(lines, expected_sizes)):
        cols = line.split("|")
        actual_size = cols[3]
        assert actual_size == expected_size, (
            f"Line {i+1} of '{REPORT_PSV}': fourth column (size_bytes) does not match.\n"
            f"  Expected: {expected_size!r}\n"
            f"  Actual:   {actual_size!r}"
        )


def test_report_psv_upload_date_column():
    with open(REPORT_PSV, "r") as f:
        content = f.read()

    lines = content.rstrip("\n").splitlines()

    expected_dates = [
        "upload_date",
        "2024-01-15",
        "2024-01-22",
        "2024-02-03",
        "2024-02-18",
        "2024-03-07",
    ]

    for i, (line, expected_date) in enumerate(zip(lines, expected_dates)):
        cols = line.split("|")
        actual_date = cols[4]
        assert actual_date == expected_date, (
            f"Line {i+1} of '{REPORT_PSV}': fifth column (upload_date) does not match.\n"
            f"  Expected: {expected_date!r}\n"
            f"  Actual:   {actual_date!r}"
        )


def test_source_files_unchanged():
    """Verify that the source files were not modified during the task."""
    expected_inventory_lines = [
        "artifact_name|version|arch|checksum_sha256|size_bytes|upload_date",
        "libssl.so.1.1|1.1.1n|x86_64|a3f1c29d8e4b56f0123456789abcdef0123456789abcdef0123456789abcdef01|2097152|2024-01-15",
        "libcurl.so.4|7.88.1|x86_64|b4e2d30a9f5c67e1234567890bcdef1234567890bcdef1234567890bcdef1234|1048576|2024-01-22",
        "nginx-1.24.0|1.24.0|aarch64|c5f3e41baf6d78f2345678901cdef2345678901cdef2345678901cdef234567|5242880|2024-02-03",
        "python3.11|3.11.4|x86_64|d6a4f52cbg7e89034567890123ef3456789012ef3456789012ef3456789012ef|31457280|2024-02-18",
        "redis-server|7.0.11|aarch64|e7b5063dch8f90145678901234f04567890123f04567890123f04567890123f0|8388608|2024-03-07",
    ]

    with open(INVENTORY_PSV, "r") as f:
        content = f.read()
    lines = content.rstrip("\n").splitlines()

    assert lines == expected_inventory_lines, (
        f"Source file '{INVENTORY_PSV}' was modified during the task. "
        "The original inventory file must remain unchanged."
    )

    expected_repo_ids_lines = ["repo_id", "R001", "R002", "R003", "R004", "R005"]

    with open(REPO_IDS_TXT, "r") as f:
        content = f.read()
    lines = content.rstrip("\n").splitlines()

    assert lines == expected_repo_ids_lines, (
        f"Source file '{REPO_IDS_TXT}' was modified during the task. "
        "The original repo_ids file must remain unchanged."
    )