FROM unix101-base:latest

USER root
RUN printf "process\nproduce\nproduct\nproject\nprovide\nprogram\npromote\npronounce\npropel\nprofile\nproblem\nprobation\nprogress\nproud\nprone\nprong\nprospect\nprotest\nprototype\npro\nprotect\nprobe\nprobate\nprose\nprone\nprofessor\nprodigy\nprophecy\nprolong\nprosper\nproton\nprotractor\nprolific\npromise\nprodigal\nprong\npropane\nproceed\nproof\npronoun\nproclaim\nprovide\nprohibit\npronto\nprodigy\npronounce\nprone\nproficiency\nprodigy\n" > /home/user/words.txt
RUN chown -R user:user /home/user
RUN chown -R user:user /home/user

USER user
WORKDIR /home/user

