#!/bin/bash
set -e
cd /home/user

mkdir -p /home/user/audit && cat > /home/user/audit/generate_report.py << 'EOF'
import csv
from datetime import datetime, timedelta, timezone
import os

os.makedirs('/home/user/audit', exist_ok=True)

# Read CSV
events = []
with open('/home/user/audit/events.csv', 'r') as f:
    reader = csv.DictReader(f)
    for row in reader:
        events.append(row)

# EDT = UTC-4
edt_offset = timezone(timedelta(hours=-4))

converted_events = []
for event in events:
    ts_utc = datetime.fromisoformat(event['timestamp_utc'].replace('Z', '+00:00'))
    ts_edt = ts_utc.astimezone(edt_offset)
    ts_str = ts_edt.strftime('%Y-%m-%d %H:%M:%S') + ' EDT'
    converted_events.append({
        'timestamp': ts_str,
        'user': event['user'],
        'action': event['action'],
        'resource': event['resource']
    })

separator = '-' * 50

lines = []
lines.append('AUDIT TRAIL REPORT')
lines.append('Generated for timezone: US/Eastern')
lines.append('Report date: 2024-06-15')
lines.append(separator)
lines.append(f"{'TIMESTAMP (EDT)':<25}{'USER':<7}{'ACTION':<11}RESOURCE")
lines.append(separator)

for ev in converted_events:
    # timestamp string is 23 chars, then 2 spaces = 25 chars total
    line = f"{ev['timestamp']}  {ev['user']:<7}{ev['action']:<11}{ev['resource']}"
    lines.append(line)

lines.append(separator)
lines.append(f"Total events: {len(converted_events)}")

users = sorted(set(ev['user'] for ev in converted_events))
lines.append(f"Users active: {', '.join(users)}")

report_content = '\n'.join(lines) + '\n'

with open('/home/user/audit/audit_report.txt', 'w') as f:
    f.write(report_content)

print("Report written successfully.")

# Append to system_audit.log using last event's timestamp
last_ts = converted_events[-1]['timestamp']
log_line = f"[{last_ts}] REPORT_GENERATED by analyst: audit_report.txt ({len(converted_events)} records)\n"

with open('/home/user/audit/system_audit.log', 'a') as f:
    f.write(log_line)

print("Log entry appended successfully.")
EOF
python3 /home/user/audit/generate_report.py
cat /home/user/audit/audit_report.txt
cat /home/user/audit/system_audit.log
