#!/bin/bash
set -e
cd /home/user

find /home/user/iot_staging -type f | sort
find /home/user/iot_staging -type f \( -name "*.tmp" -o -name "*.bak" \) | xargs rm -f
find /home/user/iot_staging -type f -name "*.conf" | xargs chmod 640
find /home/user/iot_staging -type f -name "*.bin" | xargs chmod 750
find /home/user/iot_staging -type f -name "*.bin" | sort | xargs sha256sum > /home/user/iot_staging/checksums.sha256
{ echo "=== IoT Deployment Manifest ==="; echo "Generated by: edge-deploy-prep"; echo ""; echo "[CONFIG FILES]"; find /home/user/iot_staging -type f -name "*.conf" | sort | xargs stat -c '%n: %a' | sed 's|/home/user/iot_staging/||'; echo ""; echo "[BINARY FILES]"; find /home/user/iot_staging -type f -name "*.bin" | sort | xargs stat -c '%n: %a' | sed 's|/home/user/iot_staging/||'; echo ""; echo "[CHECKSUM FILE]"; echo "checksums.sha256: present"; } > /home/user/iot_staging/manifest.txt
cat /home/user/iot_staging/manifest.txt
cat /home/user/iot_staging/checksums.sha256
find /home/user/iot_staging -type f \( -name "*.tmp" -o -name "*.bak" \) | sort
