# test_final_state.py

import os
import pytest

DATASETS_DIR = "/home/user/datasets"
REPORT_PATH = os.path.join(DATASETS_DIR, "audit_report.txt")

EXPECTED_REPORT = """\
=== DATASET AUDIT REPORT ===

DATASET SUMMARY (sorted by total size, descending):
  imaging: 8170 bytes, 4 files, largest: scan001.bin
  genomics: 5700 bytes, 3 files, largest: reference.bin
  climate: 4000 bytes, 3 files, largest: temperatures.csv
  text_corpus: 1800 bytes, 2 files, largest: articles.txt

TOTAL STORAGE USED: 19670 bytes across 12 files

LARGE FILES (>2000 bytes, sorted by size descending):
  imaging/scan001.bin: 4100 bytes
  genomics/reference.bin: 3500 bytes
  imaging/scan002.bin: 3200 bytes
  climate/temperatures.csv: 2500 bytes

TOP DATASET: imaging"""

EXPECTED_FILES = {
    "genomics/reference.bin": (3500, "A"),
    "genomics/samples.csv": (1800, "B"),
    "genomics/notes.txt": (400, "C"),
    "climate/temperatures.csv": (2500, "D"),
    "climate/metadata.json": (900, "E"),
    "climate/errors.log": (600, "F"),
    "imaging/scan001.bin": (4100, "G"),
    "imaging/scan002.bin": (3200, "H"),
    "imaging/labels.csv": (750, "I"),
    "imaging/readme.txt": (120, "J"),
    "text_corpus/articles.txt": (1500, "K"),
    "text_corpus/stopwords.txt": (300, "L"),
}

EXPECTED_SUBDIRS = ["genomics", "climate", "imaging", "text_corpus"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def read_report():
    with open(REPORT_PATH, "r") as f:
        return f.read()


# ---------------------------------------------------------------------------
# Report existence and basic properties
# ---------------------------------------------------------------------------

def test_report_file_exists():
    assert os.path.isfile(REPORT_PATH), (
        f"audit_report.txt does not exist at {REPORT_PATH}. "
        "The report must be generated by the task."
    )


def test_report_exact_content():
    actual = read_report()
    # Strip a single trailing newline if present (common with text editors)
    actual_stripped = actual.rstrip("\n")
    expected_stripped = EXPECTED_REPORT.rstrip("\n")
    assert actual_stripped == expected_stripped, (
        f"audit_report.txt content does not match expected.\n"
        f"--- EXPECTED ---\n{EXPECTED_REPORT}\n"
        f"--- ACTUAL ---\n{actual}"
    )


# ---------------------------------------------------------------------------
# Line-by-line structural checks (provide granular failure messages)
# ---------------------------------------------------------------------------

def get_report_lines():
    return read_report().rstrip("\n").splitlines()


def test_report_header_line():
    lines = get_report_lines()
    assert lines[0] == "=== DATASET AUDIT REPORT ===", (
        f"First line of report is wrong.\n"
        f"Expected: '=== DATASET AUDIT REPORT ==='\n"
        f"Got:      '{lines[0]}'"
    )


def test_report_blank_line_after_header():
    lines = get_report_lines()
    assert len(lines) > 1 and lines[1] == "", (
        f"Expected a blank line after the header (line 2), got: '{lines[1] if len(lines) > 1 else '<missing>'}'"
    )


def test_report_dataset_summary_heading():
    lines = get_report_lines()
    assert len(lines) > 2 and lines[2] == "DATASET SUMMARY (sorted by total size, descending):", (
        f"Line 3 should be 'DATASET SUMMARY (sorted by total size, descending):'\n"
        f"Got: '{lines[2] if len(lines) > 2 else '<missing>'}'"
    )


def test_report_dataset_summary_entries():
    lines = get_report_lines()
    expected_entries = [
        "  imaging: 8170 bytes, 4 files, largest: scan001.bin",
        "  genomics: 5700 bytes, 3 files, largest: reference.bin",
        "  climate: 4000 bytes, 3 files, largest: temperatures.csv",
        "  text_corpus: 1800 bytes, 2 files, largest: articles.txt",
    ]
    # Lines 3..6 (0-indexed) are the dataset summary entries
    for i, expected_line in enumerate(expected_entries):
        line_idx = 3 + i
        actual_line = lines[line_idx] if len(lines) > line_idx else "<missing>"
        assert actual_line == expected_line, (
            f"Dataset summary entry {i+1} is wrong.\n"
            f"Expected: '{expected_line}'\n"
            f"Got:      '{actual_line}'"
        )


def test_report_blank_line_before_total():
    lines = get_report_lines()
    # After 4 dataset lines (indices 3-6), index 7 should be blank
    assert len(lines) > 7 and lines[7] == "", (
        f"Expected blank line before TOTAL STORAGE USED (line 8), got: '{lines[7] if len(lines) > 7 else '<missing>'}'"
    )


def test_report_total_storage_line():
    lines = get_report_lines()
    expected = "TOTAL STORAGE USED: 19670 bytes across 12 files"
    actual = lines[8] if len(lines) > 8 else "<missing>"
    assert actual == expected, (
        f"TOTAL STORAGE USED line is wrong.\n"
        f"Expected: '{expected}'\n"
        f"Got:      '{actual}'"
    )


def test_report_blank_line_before_large_files():
    lines = get_report_lines()
    assert len(lines) > 9 and lines[9] == "", (
        f"Expected blank line before LARGE FILES section (line 10), got: '{lines[9] if len(lines) > 9 else '<missing>'}'"
    )


def test_report_large_files_heading():
    lines = get_report_lines()
    expected = "LARGE FILES (>2000 bytes, sorted by size descending):"
    actual = lines[10] if len(lines) > 10 else "<missing>"
    assert actual == expected, (
        f"LARGE FILES heading is wrong.\n"
        f"Expected: '{expected}'\n"
        f"Got:      '{actual}'"
    )


def test_report_large_files_entries():
    lines = get_report_lines()
    expected_entries = [
        "  imaging/scan001.bin: 4100 bytes",
        "  genomics/reference.bin: 3500 bytes",
        "  imaging/scan002.bin: 3200 bytes",
        "  climate/temperatures.csv: 2500 bytes",
    ]
    for i, expected_line in enumerate(expected_entries):
        line_idx = 11 + i
        actual_line = lines[line_idx] if len(lines) > line_idx else "<missing>"
        assert actual_line == expected_line, (
            f"Large files entry {i+1} is wrong.\n"
            f"Expected: '{expected_line}'\n"
            f"Got:      '{actual_line}'"
        )


def test_report_blank_line_before_top_dataset():
    lines = get_report_lines()
    # After 4 large file entries (indices 11-14), index 15 should be blank
    assert len(lines) > 15 and lines[15] == "", (
        f"Expected blank line before TOP DATASET (line 16), got: '{lines[15] if len(lines) > 15 else '<missing>'}'"
    )


def test_report_top_dataset_line():
    lines = get_report_lines()
    expected = "TOP DATASET: imaging"
    actual = lines[16] if len(lines) > 16 else "<missing>"
    assert actual == expected, (
        f"TOP DATASET line is wrong.\n"
        f"Expected: '{expected}'\n"
        f"Got:      '{actual}'"
    )


def test_report_total_line_count():
    lines = get_report_lines()
    # 17 lines total (indices 0-16)
    assert len(lines) == 17, (
        f"Report has {len(lines)} lines, expected exactly 17.\n"
        f"Lines:\n" + "\n".join(f"  [{i}] {repr(l)}" for i, l in enumerate(lines))
    )


# ---------------------------------------------------------------------------
# Verify report does NOT count itself in statistics
# ---------------------------------------------------------------------------

def test_report_not_counted_in_totals():
    """audit_report.txt must not be included in byte/file counts."""
    report_size = os.stat(REPORT_PATH).st_size
    # Grand total in report is 19670; if report were included it would differ
    lines = get_report_lines()
    total_line = next((l for l in lines if l.startswith("TOTAL STORAGE USED:")), None)
    assert total_line is not None, "TOTAL STORAGE USED line not found in report"
    assert "19670" in total_line, (
        f"Grand total should be 19670 bytes (excluding audit_report.txt), "
        f"but got: '{total_line}'"
    )
    assert "12 files" in total_line, (
        f"File count should be 12 (excluding audit_report.txt), "
        f"but got: '{total_line}'"
    )


# ---------------------------------------------------------------------------
# Verify original dataset files are untouched
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("rel_path,expected", list(EXPECTED_FILES.items()))
def test_original_file_still_exists(rel_path, expected):
    full_path = os.path.join(DATASETS_DIR, rel_path)
    assert os.path.isfile(full_path), (
        f"Original dataset file is missing after task: {full_path}"
    )


@pytest.mark.parametrize("rel_path,expected", list(EXPECTED_FILES.items()))
def test_original_file_size_unchanged(rel_path, expected):
    expected_size, _ = expected
    full_path = os.path.join(DATASETS_DIR, rel_path)
    actual_size = os.stat(full_path).st_size
    assert actual_size == expected_size, (
        f"File {full_path} has size {actual_size} bytes after task, "
        f"expected {expected_size} bytes (file may have been modified)"
    )


@pytest.mark.parametrize("subdir", EXPECTED_SUBDIRS)
def test_no_extra_files_in_subdir(subdir):
    """No unexpected files should appear in dataset subdirectories."""
    full_subdir = os.path.join(DATASETS_DIR, subdir)
    expected_filenames = {
        os.path.basename(rel_path)
        for rel_path in EXPECTED_FILES
        if rel_path.startswith(subdir + "/")
    }
    actual_files = set(
        e for e in os.listdir(full_subdir)
        if os.path.isfile(os.path.join(full_subdir, e))
    )
    unexpected = actual_files - expected_filenames
    assert not unexpected, (
        f"Unexpected files found in {full_subdir}: {unexpected}"
    )


def test_no_extra_subdirectories():
    entries = os.listdir(DATASETS_DIR)
    subdirs = [
        e for e in entries
        if os.path.isdir(os.path.join(DATASETS_DIR, e))
    ]
    unexpected = set(subdirs) - set(EXPECTED_SUBDIRS)
    assert not unexpected, (
        f"Unexpected subdirectories found in {DATASETS_DIR}: {unexpected}"
    )


def test_only_audit_report_at_top_level():
    """Only audit_report.txt should be a file directly in DATASETS_DIR."""
    top_level_files = [
        e for e in os.listdir(DATASETS_DIR)
        if os.path.isfile(os.path.join(DATASETS_DIR, e))
    ]
    assert top_level_files == ["audit_report.txt"] or set(top_level_files) == {"audit_report.txt"}, (
        f"Unexpected files at top level of {DATASETS_DIR}: "
        f"{set(top_level_files) - {'audit_report.txt'}}"
    )