# test_final_state.py

import os
import stat
import pytest

ARTIFACT_MANAGER_DIR = "/home/user/artifact-manager"
REPOS_CONF_PATH = "/home/user/artifact-manager/repos.conf"
STORAGE_DIR = "/home/user/artifact-manager/storage"
MANIFEST_PATH = "/home/user/artifact-manager/storage/MANIFEST"

EXPECTED_REPOS = [
    ("libs-release", "maven", "90"),
    ("libs-snapshot", "maven", "14"),
    ("docker-local", "docker", "30"),
    ("pypi-internal", "pypi", "60"),
    ("raw-binaries", "generic", "180"),
]

EXPECTED_MANIFEST_CONTENT = (
    "# Artifact Repository Manifest\n"
    "# Generated by: artifact-manager\n"
    "repos: 5\n"
    "\n"
    "[libs-release]\n"
    "type=maven\n"
    "retention_days=90\n"
    "path=storage/libs-release\n"
    "\n"
    "[libs-snapshot]\n"
    "type=maven\n"
    "retention_days=14\n"
    "path=storage/libs-snapshot\n"
    "\n"
    "[docker-local]\n"
    "type=docker\n"
    "retention_days=30\n"
    "path=storage/docker-local\n"
    "\n"
    "[pypi-internal]\n"
    "type=pypi\n"
    "retention_days=60\n"
    "path=storage/pypi-internal\n"
    "\n"
    "[raw-binaries]\n"
    "type=generic\n"
    "retention_days=180\n"
    "path=storage/raw-binaries\n"
)


def get_octal_permissions(path):
    """Return the octal permission bits (as a 3-digit string) for a given path."""
    st = os.stat(path)
    mode = stat.S_IMODE(st.st_mode)
    return oct(mode)[-3:]


# --- Storage directory tests ---

def test_storage_dir_exists():
    assert os.path.isdir(STORAGE_DIR), (
        f"Storage directory {STORAGE_DIR} does not exist. "
        "It must be created as part of the task."
    )


# --- Repository subdirectory tests ---

@pytest.mark.parametrize("repo_name,repo_type,retention_days", EXPECTED_REPOS)
def test_repo_subdirectory_exists(repo_name, repo_type, retention_days):
    repo_dir = os.path.join(STORAGE_DIR, repo_name)
    assert os.path.isdir(repo_dir), (
        f"Repository directory {repo_dir} does not exist. "
        f"Expected a directory for repo '{repo_name}' under {STORAGE_DIR}."
    )


@pytest.mark.parametrize("repo_name,repo_type,retention_days", EXPECTED_REPOS)
def test_repo_subdirectory_permissions(repo_name, repo_type, retention_days):
    repo_dir = os.path.join(STORAGE_DIR, repo_name)
    assert os.path.isdir(repo_dir), (
        f"Repository directory {repo_dir} does not exist, cannot check permissions."
    )
    perms = get_octal_permissions(repo_dir)
    assert perms == "750", (
        f"Repository directory {repo_dir} has permissions {perms}, "
        f"but expected 750 (rwxr-x---)."
    )


def test_no_extra_repo_subdirectories():
    """Ensure there are no unexpected subdirectories under storage/."""
    if not os.path.isdir(STORAGE_DIR):
        pytest.skip(f"{STORAGE_DIR} does not exist; skipping extra-directory check.")
    expected_names = {repo_name for repo_name, _, _ in EXPECTED_REPOS}
    actual_dirs = {
        entry.name
        for entry in os.scandir(STORAGE_DIR)
        if entry.is_dir()
    }
    extra = actual_dirs - expected_names
    assert not extra, (
        f"Unexpected subdirectories found under {STORAGE_DIR}: {sorted(extra)}. "
        f"Only these directories should exist: {sorted(expected_names)}."
    )


# --- MANIFEST file tests ---

def test_manifest_file_exists():
    assert os.path.isfile(MANIFEST_PATH), (
        f"MANIFEST file {MANIFEST_PATH} does not exist. "
        "It must be created as part of the task."
    )


def test_manifest_file_permissions():
    assert os.path.isfile(MANIFEST_PATH), (
        f"MANIFEST file {MANIFEST_PATH} does not exist, cannot check permissions."
    )
    perms = get_octal_permissions(MANIFEST_PATH)
    assert perms == "640", (
        f"MANIFEST file {MANIFEST_PATH} has permissions {perms}, "
        f"but expected 640 (rw-r-----)."
    )


def test_manifest_file_content_exact():
    assert os.path.isfile(MANIFEST_PATH), (
        f"MANIFEST file {MANIFEST_PATH} does not exist, cannot check content."
    )
    with open(MANIFEST_PATH, "r") as f:
        actual_content = f.read()
    assert actual_content == EXPECTED_MANIFEST_CONTENT, (
        f"MANIFEST file content does not match expected.\n\n"
        f"--- EXPECTED (repr) ---\n{repr(EXPECTED_MANIFEST_CONTENT)}\n\n"
        f"--- ACTUAL (repr) ---\n{repr(actual_content)}\n\n"
        f"--- EXPECTED ---\n{EXPECTED_MANIFEST_CONTENT}\n"
        f"--- ACTUAL ---\n{actual_content}"
    )


def test_manifest_header_line_repo_count():
    """Check that the 'repos:' line reflects the correct count."""
    if not os.path.isfile(MANIFEST_PATH):
        pytest.skip(f"{MANIFEST_PATH} does not exist.")
    with open(MANIFEST_PATH, "r") as f:
        lines = f.readlines()
    repos_lines = [l.strip() for l in lines if l.startswith("repos:")]
    assert len(repos_lines) == 1, (
        f"Expected exactly one 'repos:' line in MANIFEST, found {len(repos_lines)}."
    )
    assert repos_lines[0] == "repos: 5", (
        f"Expected 'repos: 5' in MANIFEST header, but got '{repos_lines[0]}'."
    )


def test_manifest_no_trailing_blank_line():
    """Verify the MANIFEST file does not end with a trailing blank line."""
    if not os.path.isfile(MANIFEST_PATH):
        pytest.skip(f"{MANIFEST_PATH} does not exist.")
    with open(MANIFEST_PATH, "r") as f:
        content = f.read()
    assert not content.endswith("\n\n"), (
        f"MANIFEST file {MANIFEST_PATH} ends with a trailing blank line, but it should not. "
        "The file must end with a single newline after the last 'path=' line."
    )
    assert content.endswith("\n"), (
        f"MANIFEST file {MANIFEST_PATH} does not end with a newline. "
        "The file must end with exactly one newline after the last 'path=' line."
    )


def test_manifest_repo_blocks_order_and_content():
    """Check each repo block appears in the correct order with correct fields."""
    if not os.path.isfile(MANIFEST_PATH):
        pytest.skip(f"{MANIFEST_PATH} does not exist.")
    with open(MANIFEST_PATH, "r") as f:
        content = f.read()

    for i, (repo_name, repo_type, retention_days) in enumerate(EXPECTED_REPOS):
        block_header = f"[{repo_name}]"
        assert block_header in content, (
            f"Block header '{block_header}' not found in MANIFEST."
        )
        expected_type_line = f"type={repo_type}"
        assert expected_type_line in content, (
            f"Expected line '{expected_type_line}' not found in MANIFEST for repo '{repo_name}'."
        )
        expected_retention_line = f"retention_days={retention_days}"
        assert expected_retention_line in content, (
            f"Expected line '{expected_retention_line}' not found in MANIFEST for repo '{repo_name}'."
        )
        expected_path_line = f"path=storage/{repo_name}"
        assert expected_path_line in content, (
            f"Expected line '{expected_path_line}' not found in MANIFEST for repo '{repo_name}'."
        )

    # Check ordering: each repo block header appears after the previous one
    positions = []
    for repo_name, _, _ in EXPECTED_REPOS:
        pos = content.find(f"[{repo_name}]")
        positions.append((repo_name, pos))

    for idx in range(1, len(positions)):
        prev_name, prev_pos = positions[idx - 1]
        curr_name, curr_pos = positions[idx]
        assert curr_pos > prev_pos, (
            f"Repo block '[{curr_name}]' appears before '[{prev_name}]' in MANIFEST, "
            f"but it should appear after. Check the order matches repos.conf."
        )


def test_manifest_comment_lines():
    """Verify the two comment lines are present in the header."""
    if not os.path.isfile(MANIFEST_PATH):
        pytest.skip(f"{MANIFEST_PATH} does not exist.")
    with open(MANIFEST_PATH, "r") as f:
        lines = f.readlines()
    assert len(lines) >= 2, (
        f"MANIFEST file has fewer than 2 lines; missing header comment lines."
    )
    assert lines[0].rstrip("\n") == "# Artifact Repository Manifest", (
        f"First line of MANIFEST should be '# Artifact Repository Manifest', "
        f"but got: {repr(lines[0].rstrip())}"
    )
    assert lines[1].rstrip("\n") == "# Generated by: artifact-manager", (
        f"Second line of MANIFEST should be '# Generated by: artifact-manager', "
        f"but got: {repr(lines[1].rstrip())}"
    )


# --- repos.conf still intact ---

def test_repos_conf_still_exists():
    assert os.path.isfile(REPOS_CONF_PATH), (
        f"repos.conf at {REPOS_CONF_PATH} no longer exists. "
        "The configuration file must not be removed or moved."
    )


def test_repos_conf_content_unchanged():
    expected_content = (
        "libs-release:maven:90\n"
        "libs-snapshot:maven:14\n"
        "docker-local:docker:30\n"
        "pypi-internal:pypi:60\n"
        "raw-binaries:generic:180"
    )
    with open(REPOS_CONF_PATH, "r") as f:
        actual = f.read().strip()
    assert actual == expected_content.strip(), (
        f"repos.conf content has been modified.\n"
        f"Expected:\n{expected_content}\n\n"
        f"Got:\n{actual}"
    )