#!/bin/bash
set -e
cd /home/user

ls /home/user/diagnostics/
cat /home/user/diagnostics/open_ports.txt
cat /home/user/diagnostics/processes.txt
cat /home/user/diagnostics/crontabs.txt
cat /home/user/diagnostics/passwd.txt
cat /home/user/diagnostics/suid_files.txt
cat /home/user/diagnostics/file_perms.txt
mkdir -p /home/user/report && cat > /home/user/report/security_report.txt << 'EOF'
=== SECURITY DIAGNOSTIC REPORT ===
Generated by: support-diagnostics v1.0

--- OPEN PORTS ---
Listening ports: 7
Suspicious ports (not in: 22,80,443,3306,5432): 4444,8080,31337

--- PROCESSES ---
Total processes: 11
Root processes: 6
Suspicious process names: nc,socat,xmrig

--- CRONTAB ENTRIES ---
Total cron entries: 6
Entries running as root: 4
Suspicious cron commands: 3

--- SUID BINARIES ---
Total SUID files: 11
Non-standard SUID files: /home/user/.local/suidshell,/opt/tools/privesc,/tmp/rootkit

--- PASSWD FILE ---
Total user accounts: 11
Accounts with UID 0: backdoor,root
Accounts with empty passwords: backdoor

--- RISK SUMMARY ---
Critical findings: 14
Risk level: CRITICAL
EOF
cat /home/user/report/security_report.txt
