# test_final_state.py

import os
import pytest

REPORT_PATH = "/home/user/report/security_report.txt"
REPORT_DIR = "/home/user/report"

EXPECTED_CONTENT = """\
=== SECURITY DIAGNOSTIC REPORT ===
Generated by: support-diagnostics v1.0

--- OPEN PORTS ---
Listening ports: 7
Suspicious ports (not in: 22,80,443,3306,5432): 4444,8080,31337

--- PROCESSES ---
Total processes: 11
Root processes: 6
Suspicious process names: nc,socat,xmrig

--- CRONTAB ENTRIES ---
Total cron entries: 6
Entries running as root: 4
Suspicious cron commands: 3

--- SUID BINARIES ---
Total SUID files: 11
Non-standard SUID files: /home/user/.local/suidshell,/opt/tools/privesc,/tmp/rootkit

--- PASSWD FILE ---
Total user accounts: 11
Accounts with UID 0: backdoor,root
Accounts with empty passwords: backdoor

--- RISK SUMMARY ---
Critical findings: 14
Risk level: CRITICAL"""


def read_report():
    with open(REPORT_PATH, "r") as f:
        return f.read()


# ---------------------------------------------------------------------------
# Directory / file existence
# ---------------------------------------------------------------------------

def test_report_directory_exists():
    assert os.path.isdir(REPORT_DIR), (
        f"Report directory {REPORT_DIR} does not exist. "
        "Create it and place the report inside."
    )


def test_report_file_exists():
    assert os.path.isfile(REPORT_PATH), (
        f"Report file {REPORT_PATH} does not exist. "
        "The task requires producing this file."
    )


def test_report_file_is_readable():
    assert os.access(REPORT_PATH, os.R_OK), (
        f"Report file {REPORT_PATH} exists but is not readable."
    )


def test_report_file_not_empty():
    content = read_report()
    assert content.strip(), (
        f"Report file {REPORT_PATH} is empty."
    )


# ---------------------------------------------------------------------------
# Full content match
# ---------------------------------------------------------------------------

def test_report_exact_content():
    content = read_report()
    # Normalise line endings
    actual = content.rstrip("\n")
    expected = EXPECTED_CONTENT.rstrip("\n")
    assert actual == expected, (
        f"Report content does not match expected.\n"
        f"--- EXPECTED ---\n{expected}\n"
        f"--- ACTUAL ---\n{actual}\n"
        f"--- DIFF (expected vs actual) ---\n"
        + _diff(expected, actual)
    )


def _diff(expected, actual):
    import difflib
    diff = difflib.unified_diff(
        expected.splitlines(keepends=True),
        actual.splitlines(keepends=True),
        fromfile="expected",
        tofile="actual",
    )
    return "".join(diff)


# ---------------------------------------------------------------------------
# Individual section checks (granular failure messages)
# ---------------------------------------------------------------------------

def _get_lines():
    return read_report().splitlines()


def _find_line(prefix):
    """Return the first line that starts with the given prefix, or None."""
    for line in _get_lines():
        if line.startswith(prefix):
            return line
    return None


def test_header_present():
    lines = _get_lines()
    assert lines[0] == "=== SECURITY DIAGNOSTIC REPORT ===", (
        f"First line of report should be '=== SECURITY DIAGNOSTIC REPORT ===' "
        f"but got: {lines[0]!r}"
    )


def test_generated_by_line():
    line = _find_line("Generated by:")
    assert line is not None, "Missing 'Generated by:' line in report."
    assert line == "Generated by: support-diagnostics v1.0", (
        f"'Generated by:' line is wrong: {line!r}"
    )


# --- OPEN PORTS ---

def test_listening_ports_count():
    line = _find_line("Listening ports:")
    assert line is not None, "Missing 'Listening ports:' line in report."
    assert line == "Listening ports: 7", (
        f"Expected 'Listening ports: 7' but got: {line!r}"
    )


def test_suspicious_ports():
    line = _find_line("Suspicious ports (not in:")
    assert line is not None, "Missing 'Suspicious ports' line in report."
    assert line == "Suspicious ports (not in: 22,80,443,3306,5432): 4444,8080,31337", (
        f"Suspicious ports line is wrong: {line!r}\n"
        "Expected ports 4444, 8080, 31337 (sorted numerically, comma-separated, no spaces)."
    )


# --- PROCESSES ---

def test_total_processes():
    line = _find_line("Total processes:")
    assert line is not None, "Missing 'Total processes:' line in report."
    assert line == "Total processes: 11", (
        f"Expected 'Total processes: 11' but got: {line!r}"
    )


def test_root_processes():
    line = _find_line("Root processes:")
    assert line is not None, "Missing 'Root processes:' line in report."
    assert line == "Root processes: 6", (
        f"Expected 'Root processes: 6' but got: {line!r}"
    )


def test_suspicious_process_names():
    line = _find_line("Suspicious process names:")
    assert line is not None, "Missing 'Suspicious process names:' line in report."
    assert line == "Suspicious process names: nc,socat,xmrig", (
        f"Suspicious process names line is wrong: {line!r}\n"
        "Expected 'nc,socat,xmrig' (sorted alphabetically, comma-separated, no spaces)."
    )


# --- CRONTAB ENTRIES ---

def test_total_cron_entries():
    line = _find_line("Total cron entries:")
    assert line is not None, "Missing 'Total cron entries:' line in report."
    assert line == "Total cron entries: 6", (
        f"Expected 'Total cron entries: 6' but got: {line!r}"
    )


def test_cron_entries_running_as_root():
    line = _find_line("Entries running as root:")
    assert line is not None, "Missing 'Entries running as root:' line in report."
    assert line == "Entries running as root: 4", (
        f"Expected 'Entries running as root: 4' but got: {line!r}"
    )


def test_suspicious_cron_commands():
    line = _find_line("Suspicious cron commands:")
    assert line is not None, "Missing 'Suspicious cron commands:' line in report."
    assert line == "Suspicious cron commands: 3", (
        f"Expected 'Suspicious cron commands: 3' but got: {line!r}"
    )


# --- SUID BINARIES ---

def test_total_suid_files():
    line = _find_line("Total SUID files:")
    assert line is not None, "Missing 'Total SUID files:' line in report."
    assert line == "Total SUID files: 11", (
        f"Expected 'Total SUID files: 11' but got: {line!r}"
    )


def test_non_standard_suid_files():
    line = _find_line("Non-standard SUID files:")
    assert line is not None, "Missing 'Non-standard SUID files:' line in report."
    expected = "Non-standard SUID files: /home/user/.local/suidshell,/opt/tools/privesc,/tmp/rootkit"
    assert line == expected, (
        f"Non-standard SUID files line is wrong: {line!r}\n"
        f"Expected: {expected!r}\n"
        "Paths should be sorted alphabetically, comma-separated, no spaces."
    )


# --- PASSWD FILE ---

def test_total_user_accounts():
    line = _find_line("Total user accounts:")
    assert line is not None, "Missing 'Total user accounts:' line in report."
    assert line == "Total user accounts: 11", (
        f"Expected 'Total user accounts: 11' but got: {line!r}"
    )


def test_accounts_with_uid_0():
    line = _find_line("Accounts with UID 0:")
    assert line is not None, "Missing 'Accounts with UID 0:' line in report."
    assert line == "Accounts with UID 0: backdoor,root", (
        f"Accounts with UID 0 line is wrong: {line!r}\n"
        "Expected 'backdoor,root' (sorted alphabetically, comma-separated, no spaces)."
    )


def test_accounts_with_empty_passwords():
    line = _find_line("Accounts with empty passwords:")
    assert line is not None, "Missing 'Accounts with empty passwords:' line in report."
    assert line == "Accounts with empty passwords: backdoor", (
        f"Accounts with empty passwords line is wrong: {line!r}\n"
        "Expected 'backdoor'."
    )


# --- RISK SUMMARY ---

def test_critical_findings():
    line = _find_line("Critical findings:")
    assert line is not None, "Missing 'Critical findings:' line in report."
    assert line == "Critical findings: 14", (
        f"Expected 'Critical findings: 14' but got: {line!r}\n"
        "Sum: suspicious_ports(3) + suspicious_process_names(3) + "
        "suspicious_cron_commands(3) + non_standard_suid(3) + "
        "extra_uid0_accounts(1) + empty_password_accounts(1) = 14."
    )


def test_risk_level():
    line = _find_line("Risk level:")
    assert line is not None, "Missing 'Risk level:' line in report."
    assert line == "Risk level: CRITICAL", (
        f"Expected 'Risk level: CRITICAL' (critical findings >= 5) but got: {line!r}"
    )


# --- Section headers present ---

@pytest.mark.parametrize("header", [
    "--- OPEN PORTS ---",
    "--- PROCESSES ---",
    "--- CRONTAB ENTRIES ---",
    "--- SUID BINARIES ---",
    "--- PASSWD FILE ---",
    "--- RISK SUMMARY ---",
])
def test_section_header_present(header):
    lines = _get_lines()
    assert header in lines, (
        f"Section header {header!r} not found in report."
    )