# test_final_state.py

import os
import pytest

REPORT_PATH = "/home/user/diagnostics/env_report.txt"
DOTENV_PATH = "/home/user/app/.env"
DIAGNOSTICS_DIR = "/home/user/diagnostics"


def get_report_lines():
    with open(REPORT_PATH, "r") as f:
        content = f.read()
    return content


def test_diagnostics_directory_exists():
    assert os.path.isdir(DIAGNOSTICS_DIR), (
        f"Directory {DIAGNOSTICS_DIR} does not exist. "
        "The agent must create this directory as part of the task."
    )


def test_report_file_exists():
    assert os.path.isfile(REPORT_PATH), (
        f"Report file {REPORT_PATH} does not exist. "
        "The agent must generate this file as part of the task."
    )


def test_report_ends_with_newline():
    with open(REPORT_PATH, "rb") as f:
        content = f.read()
    assert content.endswith(b"\n"), (
        f"File {REPORT_PATH} does not end with a newline character. "
        "The report must end with a newline after the last line."
    )


def test_report_line_count():
    with open(REPORT_PATH, "r") as f:
        content = f.read()
    # Strip trailing newline and split to get lines
    lines = content.rstrip("\n").split("\n")
    assert len(lines) == 19, (
        f"Expected 19 lines in {REPORT_PATH}, got {len(lines)}.\n"
        f"Lines:\n" + "\n".join(f"{i+1}: {repr(l)}" for i, l in enumerate(lines))
    )


def test_report_line1_header():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[0] == "=== ENVIRONMENT DIAGNOSTICS REPORT ===", (
        f"Line 1 expected '=== ENVIRONMENT DIAGNOSTICS REPORT ===' but got: {repr(lines[0])}"
    )


def test_report_line2_generated_by():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[1] == "Generated by: support-tool v1.0", (
        f"Line 2 expected 'Generated by: support-tool v1.0' but got: {repr(lines[1])}"
    )


def test_report_line3_empty():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[2] == "", (
        f"Line 3 expected empty line but got: {repr(lines[2])}"
    )


def test_report_line4_dotenv_section_header():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[3] == f"[DOTENV FILE: {DOTENV_PATH}]", (
        f"Line 4 expected '[DOTENV FILE: {DOTENV_PATH}]' but got: {repr(lines[3])}"
    )


def test_report_line5_app_env():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[4] == "APP_ENV=production", (
        f"Line 5 expected 'APP_ENV=production' but got: {repr(lines[4])}"
    )


def test_report_line6_app_port():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[5] == "APP_PORT=8080", (
        f"Line 6 expected 'APP_PORT=8080' but got: {repr(lines[5])}"
    )


def test_report_line7_db_host():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[6] == "DB_HOST=db.internal", (
        f"Line 7 expected 'DB_HOST=db.internal' but got: {repr(lines[6])}"
    )


def test_report_line8_db_password_redacted():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[7] == "DB_PASSWORD=***REDACTED***", (
        f"Line 8 expected 'DB_PASSWORD=***REDACTED***' but got: {repr(lines[7])}. "
        "The DB_PASSWORD value must be redacted because its key contains 'PASSWORD'."
    )


def test_report_line9_log_level():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[8] == "LOG_LEVEL=info", (
        f"Line 9 expected 'LOG_LEVEL=info' but got: {repr(lines[8])}"
    )


def test_report_line10_secret_key_redacted():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[9] == "SECRET_KEY=***REDACTED***", (
        f"Line 10 expected 'SECRET_KEY=***REDACTED***' but got: {repr(lines[9])}. "
        "The SECRET_KEY value must be redacted because its key contains 'SECRET'."
    )


def test_report_line11_empty():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[10] == "", (
        f"Line 11 expected empty line but got: {repr(lines[10])}"
    )


def test_report_line12_live_env_section_header():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[11] == "[LIVE ENVIRONMENT]", (
        f"Line 12 expected '[LIVE ENVIRONMENT]' but got: {repr(lines[11])}"
    )


def test_report_line13_hostname():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    actual_hostname = os.environ.get("HOSTNAME", "")
    assert lines[12].startswith("HOSTNAME="), (
        f"Line 13 expected to start with 'HOSTNAME=' but got: {repr(lines[12])}"
    )
    reported_value = lines[12][len("HOSTNAME="):]
    # The value must match the live HOSTNAME env var
    assert reported_value == actual_hostname, (
        f"Line 13: HOSTNAME value in report is {repr(reported_value)}, "
        f"but live $HOSTNAME is {repr(actual_hostname)}."
    )


def test_report_line14_shell():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    actual_shell = os.environ.get("SHELL", "")
    assert lines[13].startswith("SHELL="), (
        f"Line 14 expected to start with 'SHELL=' but got: {repr(lines[13])}"
    )
    reported_value = lines[13][len("SHELL="):]
    assert reported_value == actual_shell, (
        f"Line 14: SHELL value in report is {repr(reported_value)}, "
        f"but live $SHELL is {repr(actual_shell)}."
    )


def test_report_line15_user():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    actual_user = os.environ.get("USER", "")
    assert lines[14].startswith("USER="), (
        f"Line 15 expected to start with 'USER=' but got: {repr(lines[14])}"
    )
    reported_value = lines[14][len("USER="):]
    assert reported_value == actual_user, (
        f"Line 15: USER value in report is {repr(reported_value)}, "
        f"but live $USER is {repr(actual_user)}."
    )


def test_report_line16_empty():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[15] == "", (
        f"Line 16 expected empty line but got: {repr(lines[15])}"
    )


def test_report_line17_summary_header():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[16] == "[SUMMARY]", (
        f"Line 17 expected '[SUMMARY]' but got: {repr(lines[16])}"
    )


def test_report_line18_dotenv_variables_loaded():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[17] == "Dotenv variables loaded: 6", (
        f"Line 18 expected 'Dotenv variables loaded: 6' but got: {repr(lines[17])}"
    )


def test_report_line19_sensitive_keys_redacted():
    with open(REPORT_PATH, "r") as f:
        lines = f.read().rstrip("\n").split("\n")
    assert lines[18] == "Sensitive keys redacted: 2", (
        f"Line 19 expected 'Sensitive keys redacted: 2' but got: {repr(lines[18])}"
    )


def test_report_does_not_contain_raw_password():
    with open(REPORT_PATH, "r") as f:
        content = f.read()
    assert "supersecret123" not in content, (
        f"File {REPORT_PATH} contains the raw DB_PASSWORD value 'supersecret123'. "
        "Sensitive values must be redacted with '***REDACTED***'."
    )


def test_report_does_not_contain_raw_secret_key():
    with open(REPORT_PATH, "r") as f:
        content = f.read()
    assert "abc123xyz789" not in content, (
        f"File {REPORT_PATH} contains the raw SECRET_KEY value 'abc123xyz789'. "
        "Sensitive values must be redacted with '***REDACTED***'."
    )


def test_dotenv_file_still_intact():
    """Ensure the original .env file was not modified by the agent."""
    expected_content = (
        "APP_ENV=production\n"
        "APP_PORT=8080\n"
        "DB_HOST=db.internal\n"
        "DB_PASSWORD=supersecret123\n"
        "LOG_LEVEL=info\n"
        "SECRET_KEY=abc123xyz789\n"
    )
    assert os.path.isfile(DOTENV_PATH), (
        f"Original .env file {DOTENV_PATH} is missing."
    )
    with open(DOTENV_PATH, "r") as f:
        content = f.read()
    # Normalize: allow with or without trailing newline
    assert content.strip() == expected_content.strip(), (
        f"Original .env file {DOTENV_PATH} was modified.\n"
        f"Expected:\n{expected_content.strip()}\n\nGot:\n{content.strip()}"
    )