#!/bin/bash
set -e
cd /home/user

cat /home/user/artifact-manager/repos.conf
mkdir -p /home/user/artifact-manager/storage/libs-release /home/user/artifact-manager/storage/libs-snapshot /home/user/artifact-manager/storage/docker-local /home/user/artifact-manager/storage/pypi-internal /home/user/artifact-manager/storage/raw-binaries
cat > /home/user/artifact-manager/storage/MANIFEST << 'EOF'
# Artifact Repository Manifest
# Generated by: artifact-manager
repos: 5

[libs-release]
type=maven
retention_days=90
path=storage/libs-release

[libs-snapshot]
type=maven
retention_days=14
path=storage/libs-snapshot

[docker-local]
type=docker
retention_days=30
path=storage/docker-local

[pypi-internal]
type=pypi
retention_days=60
path=storage/pypi-internal

[raw-binaries]
type=generic
retention_days=180
path=storage/raw-binaries
EOF
chmod 750 /home/user/artifact-manager/storage/libs-release /home/user/artifact-manager/storage/libs-snapshot /home/user/artifact-manager/storage/docker-local /home/user/artifact-manager/storage/pypi-internal /home/user/artifact-manager/storage/raw-binaries && chmod 640 /home/user/artifact-manager/storage/MANIFEST
ls -la /home/user/artifact-manager/storage/ && echo "---" && cat /home/user/artifact-manager/storage/MANIFEST
