# test_final_state.py

import os
import pytest

AUDIT_DIR = "/home/user/audit"
EVENTS_CSV = "/home/user/audit/events.csv"
AUDIT_REPORT = "/home/user/audit/audit_report.txt"
SYSTEM_AUDIT_LOG = "/home/user/audit/system_audit.log"

EXPECTED_REPORT_CONTENT = """\
AUDIT TRAIL REPORT
Generated for timezone: US/Eastern
Report date: 2024-06-15
--------------------------------------------------
TIMESTAMP (EDT)          USER   ACTION     RESOURCE
--------------------------------------------------
2024-06-15 04:00:00 EDT  alice  LOGIN      portal
2024-06-15 09:30:00 EDT  bob    DOWNLOAD   report_q2.pdf
2024-06-15 10:15:00 EDT  alice  UPLOAD     config_backup.tar
2024-06-15 15:45:00 EDT  carol  LOGIN      portal
2024-06-15 17:00:00 EDT  bob    LOGOUT     portal
2024-06-15 19:30:00 EDT  alice  DELETE     temp_logs.zip
--------------------------------------------------
Total events: 6
Users active: alice, bob, carol
"""

EXPECTED_LOG_LINE = "[2024-06-15 19:30:00 EDT] REPORT_GENERATED by analyst: audit_report.txt (6 records)\n"

SEPARATOR = "-" * 50


# ──────────────────────────────────────────────────────────────
# audit_report.txt tests
# ──────────────────────────────────────────────────────────────

def test_audit_report_exists():
    assert os.path.isfile(AUDIT_REPORT), (
        f"Expected audit report to exist at {AUDIT_REPORT}, but it does not. "
        "The task requires creating this file."
    )


def test_audit_report_exact_content():
    with open(AUDIT_REPORT, "r") as f:
        content = f.read()
    assert content == EXPECTED_REPORT_CONTENT, (
        f"Content of {AUDIT_REPORT} does not match expected.\n\n"
        f"--- EXPECTED (repr) ---\n{EXPECTED_REPORT_CONTENT!r}\n\n"
        f"--- ACTUAL (repr) ---\n{content!r}"
    )


def test_audit_report_first_line():
    with open(AUDIT_REPORT, "r") as f:
        lines = f.readlines()
    assert lines[0].rstrip("\n") == "AUDIT TRAIL REPORT", (
        f"First line of {AUDIT_REPORT} should be 'AUDIT TRAIL REPORT', "
        f"but got: {lines[0].rstrip(chr(10))!r}"
    )


def test_audit_report_timezone_line():
    with open(AUDIT_REPORT, "r") as f:
        lines = f.readlines()
    assert lines[1].rstrip("\n") == "Generated for timezone: US/Eastern", (
        f"Second line of {AUDIT_REPORT} should be 'Generated for timezone: US/Eastern', "
        f"but got: {lines[1].rstrip(chr(10))!r}"
    )


def test_audit_report_date_line():
    with open(AUDIT_REPORT, "r") as f:
        lines = f.readlines()
    assert lines[2].rstrip("\n") == "Report date: 2024-06-15", (
        f"Third line of {AUDIT_REPORT} should be 'Report date: 2024-06-15', "
        f"but got: {lines[2].rstrip(chr(10))!r}"
    )


def test_audit_report_separator_lines():
    with open(AUDIT_REPORT, "r") as f:
        lines = [line.rstrip("\n") for line in f.readlines()]
    separator_indices = [i for i, line in enumerate(lines) if line == SEPARATOR]
    assert len(separator_indices) == 3, (
        f"Expected exactly 3 separator lines of 50 hyphens in {AUDIT_REPORT}, "
        f"but found {len(separator_indices)} at line indices {separator_indices}."
    )
    assert separator_indices[0] == 3, (
        f"First separator should be at line index 3 (line 4), but found at index {separator_indices[0]}."
    )
    assert separator_indices[1] == 5, (
        f"Second separator should be at line index 5 (line 6), but found at index {separator_indices[1]}."
    )
    assert separator_indices[2] == 12, (
        f"Third separator should be at line index 12 (line 13), but found at index {separator_indices[2]}."
    )


def test_audit_report_header_row():
    with open(AUDIT_REPORT, "r") as f:
        lines = [line.rstrip("\n") for line in f.readlines()]
    header_line = lines[4]
    expected_header = "TIMESTAMP (EDT)          USER   ACTION     RESOURCE"
    assert header_line == expected_header, (
        f"Header row in {AUDIT_REPORT} does not match.\n"
        f"Expected: {expected_header!r}\n"
        f"Actual:   {header_line!r}"
    )


def test_audit_report_data_rows():
    expected_data_rows = [
        "2024-06-15 04:00:00 EDT  alice  LOGIN      portal",
        "2024-06-15 09:30:00 EDT  bob    DOWNLOAD   report_q2.pdf",
        "2024-06-15 10:15:00 EDT  alice  UPLOAD     config_backup.tar",
        "2024-06-15 15:45:00 EDT  carol  LOGIN      portal",
        "2024-06-15 17:00:00 EDT  bob    LOGOUT     portal",
        "2024-06-15 19:30:00 EDT  alice  DELETE     temp_logs.zip",
    ]
    with open(AUDIT_REPORT, "r") as f:
        lines = [line.rstrip("\n") for line in f.readlines()]
    # Data rows are lines 6..11 (indices 6 to 11 inclusive)
    actual_data_rows = lines[6:12]
    assert len(actual_data_rows) == 6, (
        f"Expected 6 data rows in {AUDIT_REPORT}, but found {len(actual_data_rows)}."
    )
    for i, (expected, actual) in enumerate(zip(expected_data_rows, actual_data_rows)):
        assert actual == expected, (
            f"Data row {i+1} in {AUDIT_REPORT} does not match.\n"
            f"Expected: {expected!r}\n"
            f"Actual:   {actual!r}"
        )


def test_audit_report_timestamp_conversion_edt():
    """Verify each UTC timestamp was correctly converted to EDT (UTC-4)."""
    expected_timestamps = [
        "2024-06-15 04:00:00 EDT",
        "2024-06-15 09:30:00 EDT",
        "2024-06-15 10:15:00 EDT",
        "2024-06-15 15:45:00 EDT",
        "2024-06-15 17:00:00 EDT",
        "2024-06-15 19:30:00 EDT",
    ]
    with open(AUDIT_REPORT, "r") as f:
        content = f.read()
    for ts in expected_timestamps:
        assert ts in content, (
            f"Expected EDT timestamp '{ts}' to appear in {AUDIT_REPORT}, but it was not found. "
            "Check that UTC timestamps are being correctly converted to EDT (UTC-4)."
        )


def test_audit_report_total_events_line():
    with open(AUDIT_REPORT, "r") as f:
        lines = [line.rstrip("\n") for line in f.readlines()]
    total_line = lines[13]
    assert total_line == "Total events: 6", (
        f"'Total events' line in {AUDIT_REPORT} should be 'Total events: 6', "
        f"but got: {total_line!r}"
    )


def test_audit_report_users_active_line():
    with open(AUDIT_REPORT, "r") as f:
        lines = [line.rstrip("\n") for line in f.readlines()]
    users_line = lines[14]
    assert users_line == "Users active: alice, bob, carol", (
        f"'Users active' line in {AUDIT_REPORT} should be 'Users active: alice, bob, carol', "
        f"but got: {users_line!r}"
    )


def test_audit_report_no_trailing_spaces_on_resource():
    """Resources should have no trailing spaces."""
    with open(AUDIT_REPORT, "r") as f:
        lines = f.readlines()
    data_rows = lines[6:12]
    for i, row in enumerate(data_rows):
        row_stripped = row.rstrip("\n")
        assert not row_stripped.endswith(" "), (
            f"Data row {i+1} in {AUDIT_REPORT} has trailing spaces: {row_stripped!r}"
        )


def test_audit_report_column_widths():
    """Verify column widths in data rows."""
    with open(AUDIT_REPORT, "r") as f:
        lines = [line.rstrip("\n") for line in f.readlines()]
    data_rows = lines[6:12]
    for i, row in enumerate(data_rows):
        # Timestamp+timezone is 23 chars, followed by 2 spaces = chars 0..24
        ts_field = row[:25]
        ts_part = ts_field[:23]
        gap = ts_field[23:25]
        assert gap == "  ", (
            f"Data row {i+1}: expected 2 spaces after timestamp (positions 23-24), "
            f"but got {gap!r} in row: {row!r}"
        )
        # USER field: chars 25..31 (7 chars)
        user_field = row[25:32]
        assert len(user_field) == 7, (
            f"Data row {i+1}: USER field should be 7 chars wide, "
            f"but got {len(user_field)} chars: {user_field!r}"
        )
        # ACTION field: chars 32..42 (11 chars)
        action_field = row[32:43]
        assert len(action_field) == 11, (
            f"Data row {i+1}: ACTION field should be 11 chars wide, "
            f"but got {len(action_field)} chars: {action_field!r}"
        )


def test_audit_report_line_count():
    with open(AUDIT_REPORT, "r") as f:
        lines = f.readlines()
    # 15 lines of content + trailing newline means last line ends with \n
    # Lines: title, tz, date, sep, header, sep, 6 data rows, sep, total, users = 15 lines
    assert len(lines) == 15, (
        f"Expected 15 lines in {AUDIT_REPORT}, but found {len(lines)}. "
        f"Lines: {lines!r}"
    )


def test_audit_report_ends_with_newline():
    with open(AUDIT_REPORT, "rb") as f:
        content = f.read()
    assert content.endswith(b"\n"), (
        f"{AUDIT_REPORT} should end with a newline character, but it does not."
    )


# ──────────────────────────────────────────────────────────────
# system_audit.log tests
# ──────────────────────────────────────────────────────────────

def test_system_audit_log_exists():
    assert os.path.isfile(SYSTEM_AUDIT_LOG), (
        f"Expected system audit log to exist at {SYSTEM_AUDIT_LOG}, but it does not. "
        "The task requires creating/appending to this file."
    )


def test_system_audit_log_exact_content():
    with open(SYSTEM_AUDIT_LOG, "r") as f:
        content = f.read()
    assert content == EXPECTED_LOG_LINE, (
        f"Content of {SYSTEM_AUDIT_LOG} does not match expected.\n\n"
        f"--- EXPECTED (repr) ---\n{EXPECTED_LOG_LINE!r}\n\n"
        f"--- ACTUAL (repr) ---\n{content!r}"
    )


def test_system_audit_log_single_line():
    with open(SYSTEM_AUDIT_LOG, "r") as f:
        lines = [line for line in f.readlines() if line.strip()]
    assert len(lines) == 1, (
        f"Expected exactly 1 non-empty line in {SYSTEM_AUDIT_LOG}, "
        f"but found {len(lines)} lines."
    )


def test_system_audit_log_timestamp():
    with open(SYSTEM_AUDIT_LOG, "r") as f:
        content = f.read()
    expected_ts = "[2024-06-15 19:30:00 EDT]"
    assert expected_ts in content, (
        f"Expected timestamp {expected_ts!r} in {SYSTEM_AUDIT_LOG}, but it was not found. "
        "The timestamp should be the last event's converted EDT timestamp. "
        f"Actual content: {content!r}"
    )


def test_system_audit_log_report_generated():
    with open(SYSTEM_AUDIT_LOG, "r") as f:
        content = f.read()
    assert "REPORT_GENERATED by analyst: audit_report.txt (6 records)" in content, (
        f"Expected 'REPORT_GENERATED by analyst: audit_report.txt (6 records)' "
        f"in {SYSTEM_AUDIT_LOG}, but it was not found. "
        f"Actual content: {content!r}"
    )


def test_system_audit_log_ends_with_newline():
    with open(SYSTEM_AUDIT_LOG, "rb") as f:
        content = f.read()
    assert content.endswith(b"\n"), (
        f"{SYSTEM_AUDIT_LOG} should end with a newline character, but it does not."
    )


# ──────────────────────────────────────────────────────────────
# Source file integrity (should remain unchanged)
# ──────────────────────────────────────────────────────────────

def test_events_csv_still_intact():
    """The original events.csv should not have been modified."""
    expected = (
        "timestamp_utc,user,action,resource\n"
        "2024-06-15T08:00:00Z,alice,LOGIN,portal\n"
        "2024-06-15T13:30:00Z,bob,DOWNLOAD,report_q2.pdf\n"
        "2024-06-15T14:15:00Z,alice,UPLOAD,config_backup.tar\n"
        "2024-06-15T19:45:00Z,carol,LOGIN,portal\n"
        "2024-06-15T21:00:00Z,bob,LOGOUT,portal\n"
        "2024-06-15T23:30:00Z,alice,DELETE,temp_logs.zip"
    )
    with open(EVENTS_CSV, "r") as f:
        content = f.read().strip()
    assert content == expected.strip(), (
        f"The source file {EVENTS_CSV} appears to have been modified. "
        f"Expected:\n{expected}\n\nActual:\n{content}"
    )